services:
  postgres:
    image: postgres:16
    container_name: stock_analytics_postgres
    environment:
      POSTGRES_DB: investment_sbd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d investment_sbd"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
